
sonar.projectVersion=1.0.0
sonar.exclusions= ec.com.ug.tesis.web.demo/src/utils/constants/*.js, ec.com.ug.tesis.web.demo/src/lib/**.*, ec.com.ug.tesis.web.demo/src/assets/**.*, ec.com.ug.tesis.web.demo/src/registerServiceWorker.js, ec.com.ug.tesis.web.demo/src/**/*.spec.js, ec.com.ug.tesis.web.demo/src/**/index.js
sonar.sourceEncoding=UTF-8