
sonar.projectVersion=1.0.0
sonar.exclusions= net.diligentec.web.demo/src/utils/constants/*.js, net.diligentec.web.demo/src/lib/**.*, net.diligentec.web.demo/src/assets/**.*, net.diligentec.web.demo/src/registerServiceWorker.js, net.diligentec.web.demo/src/**/*.spec.js, net.diligentec.web.demo/src/**/index.js
sonar.sourceEncoding=UTF-8